apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-sample
  template:
    metadata:
      labels:
        app: eks-sample
    spec:
      containers:
        - name: web
          image: 796973495528.dkr.ecr.us-east-1.amazonaws.com/eks-sample-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
